### PR TITLE
README.md: we are in nixpkgs

### PR DESCRIPTION
**Pull request by suhr**
Merge this on the next update of [nixpkgs-channels](https://github.com/NixOS/nixpkgs-channels).

### CODE REVIEW

**Comment by kpp** [comment]
You should also add an example of configuration of tox-node

**Comment by suhr** [comment]
Done.

PS: yes, this is indeed `tcpConnectionLimit`.

**Comment by kpp** [comment]
Thanks

**Comment by kpp** [comment]
@suhr rebase on master plz

**Comment by kpp** [comment]
> Merge this on the next update of nixpkgs-channels.

DId they get updated?

**Comment by suhr** [comment]
Sure, merge it.

**Comment by kpp** [comment]
https://github.com/NixOS/nixpkgs/pull/62114

**Pull request merged**
